slab/quill

src/modules/link-tooltip.coffee, src/themes/base/modules/link-tooltip.styl
Uses `@quill.editor.doc.findLeafAt(range)` to expand the selection to include the entire contents of the anchor (assuming that the leaf found is the anchor). This assumption makes me kind of nervous... but I couldn't come up with a better way to do this.
Clicking the remove button in the tooltip always removes the link from the entire leaf.
Clicking the button in the WYSIWYG bar can remove the link from just the selected text (if the collection is not collapsed), otherwise it acts similarly to the tooltip remove button.
=> Add a remove button to the link tooltip

src/quill.coffee
Provides consistency with the setContents() method, which currently accepts
both array and delta objects as the argument.
=> Allow calling quill.updateContents() with an array

config/grunt/dist.coffee
I was having a build error when running:
`grunt dist`
```
grunt dist
Running "clean:all" (clean) task
>> 2 paths cleaned.
Running "clean:coverage" (clean) task
>> 0 paths cleaned.
Running "lodash:target" (lodash) task
Running "browserify:quill" (browserify) task
>> Error: ENOENT, open '.build/lodash.js'
Warning: Error running grunt-browserify. Use --force to continue.
Aborted due to warnings.
```
It looks like 'debug' is no longer a supported flag, at least according to what I found at https://www.npmjs.com/package/grunt-lodash:
```
// with or without the -- 
// these are the only tested options, 
// as the others don't make sense to use here 
'flags': [
'--stdout',
'development',
'--production',
'source-map'
],
```
Changing 'debug' to 'development' results in a successful `grunt dist` …
=> change lodash grunt config flag to 'development' from 'debug'

src/core/selection.coffee, test/unit/core/selection.coffee
When you focus on a line that only has a BR tag in it ie will set the start of the range always to 1 which is inconsistent with other browsers which return 0.
=> Fixes issue with calculation position from index with BR tags in ie

src/core/line.coffee, test/unit/core/line.coffee
Without this call to split(), the targetNode may outgrow leaf.length, causing
the call to format.add(targetNode, value) to operate on more than was intended.
Fixes #310
=> Ensure targetNode matches leaf.length in formatText

src/modules/image-tooltip.coffee
This fixes an issue where the image toolbar button does not update properly after an image has been deleted. In order to reproduce do the following:
1. Go to the [Quill homepage](http://quilljs.com/)
2. In the example editor select the image with your cursor (you will see the image button in the toolbar turn blue).
3. Click the image button in the toolbar.
At this point you will see that the image has been removed, but the button is still blue, seeming to indicate there is an image still present. If you select somewhere else or use the left/right keys and then come back to that same position it will be properly stay deactivated.
There were no tests for the image tooltip module unfortunately, but I based the code on the link tooltip which is somewhat similar.
=> Fix deactivation of image toolbar button after deletion.

src/modules/toolbar.coffee, src/quill.coffee
Wire up a `FORMAT_INIT` event that parallels `MODULE_INIT`, so that modules can keep track of formats added via `quill.addFormat()`.
I've refactored the toolbar class a bit so that init logic can be shared between formats passed in through options and formats added in later.
=> Make toolbar handle formats created through quill.addFormat()

src/modules/keyboard.coffee
fixed typo for format assignment.  caused issues with unordered lists
=> hotfix Keyboard._initDeletes

README.md
A minor change to the README, but might help for faster navigation (I was confused when clicking the link that I saw questions about PHP etc, since I got redirected to stackoverflow's homepage).
=> Deep-linking to quill tag on stackoverflow.

docs/modules/toolbar.md
'huge' and 'normal' are not valid values for the CSS font-size property (see https://developer.mozilla.org/en-US/docs/Web/CSS/font-size).
As a result, the sizes in the toolbar example code only work for the 'small' and 'large' options, which are valid values. 
This change updates all values to pixels, which works as expected.
=> Update toolbar documentation to use working values for font size

docs/api.md
The docs for updateContents show an example delta with startLength and endLength properties set. From reading http://quilljs.com/blog/a-new-delta/ , I believe these properties are no longer used. Removing for clarity.
=> Remove doc references to startLength and endLength

index.html
I just saw the link within the editor (when viewing the source), but didn't notice it when on the website. This change makes it easier to get to the repo.
=> link to Github repo from website

README.md
As a newcomer to the js ecosystem of build tools it wasn't exactly clear to me how to access the example pages since I was not familiar with jade or harp.  I added two links in the readme to easily access the two example pages.
=> add instructions for viewing example pages

src/modules/toolbar.coffee, src/modules/tooltip.coffee, test/fixtures/unit.html, test/unit/modules/toolbar.coffee
When using the `Quill` methods `deleteText`, `insertEmbed`, `insertText`, `setText`, `setHTML`, and `formatText` the toolbar icons will now properly update. This was accomplished by having the toolbar call `updateActive` whenever the `TEXT_CHANGE` event is triggered. Tests have been added to cover the error.
This also resolves #320.
=> Fix text change methods not updating toolbar icons

src/core/leaf.coffee
`Leaf` methods `deleteText()` and `insertText()` sometimes replace the leaf node with a new `textNode`, but neglect to call `dom(textNode).data(Leaf.DATA_KEY, this)`, breaking `line.getLeaf()` and anything that depends on it.
This fix solves the problem, eliminating mysterious side-effects, e.g., not firing `quill-selection-change` events when the selection moves to some nodes.
Alternatively, the fix could be done inside `dom.replace()` instead.
=> set leaf data when replacing leaf node

src/modules/multi-cursor.coffee
Cursors are absolutely positioned with respect to the top of the .ql-container.
quill.getBounds().top returns a smaller integer when the .ql-container is scrolled vertically.
As a result, positioning a cursor requires adding container.scrollTop to the cursor bounds.
=> Fix cursor top position in multi-cursor module when the quill container is scrolled.

src/core/editor.coffee
This ensures that the delta is as close to the user's action as
possible.
=> Generate the delta in a cursor-aware manner.

src/modules/keyboard.coffee
This fixes a bug that causes enter to fail when it's in formatted
text.
=> Enter event shouldn't assume that toolbar exists

package.json
If you don"t have `grunt-cli` globally installed, the build will currently fail.
This PR fixes this.
=> Fix build when grunt is not installed globally

src/quill.coffee
This can be useful if for e.g. the user wishes to re-implement paste.
=> Allow the document module to be require-d.

src/modules/keyboard.coffee, test/unit/modules/keyboard.coffee
This ~~fixes #386~~ fixes the situation mentioned in #386 where a single enter will clear certain formats, while leaving others in place, it does not fix the double enter issue.
There's a bug in [this each loop](https://github.com/quilljs/quill/blob/564848ee95521520118249b98bd122eaad230d27/src/modules/keyboard.coffee#L58-L61) when the CoffeeScript is converted to JavaScript. Since CoffeeScript always returns the last statement, it is returning the result of setting the format which can be false and will then drop out of the loop, not applying the remaining formats.
I also added a test to make sure that formatting is retained from now on.
=> Fix retention of formats between lines.

src/modules/paste-manager.coffee, test/unit/modules/paste-manager.coffee
This will make it easier for post-processing the pasted data without having to rewrite the paste manager or wait for the text-change event.
=> Provide a paste-manager api to customize final delta.

src/core/format.coffee, test/unit/core/format.coffee
To reproduce the bug: let's say we have text "abc", select "a", apply link "link1", then select "ab", apply link "link2" we will have the following markup: `<a href="link2"><a href="link1">a</a>b</a>c`. This is malformed url as per html standard, plus `quill.getContents()` will return text with 2 urls rather than just 1.
=> Fix nested anchor tags after applying multiple link formats.

src/modules/undo-manager.coffee, test/unit/modules/undo-manager.coffee
This allows one to mark changes that should be "undoable" by specifying source = 'user', which is useful for a collaborative editing environment in which each client maintains their own undo / redo stack (instead of sharing a global one).
=> Transform the undo/redo stacks against non-user initiated changes

src/core/editor.coffee, src/modules/multi-cursor.coffee
An example scenario:
- Two clients (client A and client B) are connected to the same document in such a way that client A's changes take 5 seconds to propagate to client B and vice versa.
- Let the initial length of the document be 100.
- Client A changes her cursor position to 95. At the same time, Client B deletes 20 characters from the beginning of the document.
- By the time Client B receives A's new cursor position, the document length is 80 characters, and the cursor position of 95 is invalid (beyond the end of the document).
The right thing to do in this scenario would be to transform Client A's cursor against the 20 character deletion. However, the amount of bookkeeping necessary to compute this diff is not trivial, and so for this edge case I prefer to just remove the offending …
=> Remove a cursor with an invalid index in _updateCursor()

src/core/line.coffee, test/unit/core/line.coffee
Sometimes, a strange looking delta may come into quill, such as:
```
// 'list' is not a valid format for inline text
{ ops: [{ insert: 'abc', attributes: { list: true }, { insert: '\n' }] }
```
Line formats like `list` are expected to only apply to line nodes (they have a parentNode, etc). When `format.add(node, value)` is called on a leaf node, especially one that is detached from the DOM, bad things may happen, such as:
```
Uncaught TypeError: Cannot read property 'replaceChild' of null
Wrapper.replace @ dom.coffee:165
Wrapper.switchTag @ dom.coffee:232
Format.add @ format.coffee:102
(anonymous function) @ line.coffee:110
```
Quill should be resilient when such a delta is passed to `quill.setContents()`, by ignoring formats in the wrong context. This change ensures that only non-line …
=> Only apply non-line formats when building a new leaf

src/modules/multi-cursor.coffee
This behavior:
Without this change, the nametag part of the cursor does not appear as new characters are inserted.
=> Show the flag while a remote user is typing like in Google Docs

src/modules/keyboard.coffee
Commit c5d2ede caused my bold / italic / underline hotkeys to stop working, because I set up all of my formats programatically through `quill.addFormat()`.
Instead of checking `@quill.options.formats`, the handler should instead check `@quill.editor.doc.formats`.
=> Alternative fix for #432 that also works with formats added via quill.addFormat()

src/modules/paste-manager.coffee
When there are multiple Quill instances on a page (for example, a form that needs to be filled in with rich text data) and you have disabled tab using the technique in https://github.com/quilljs/quill/issues/110, it takes about 6 hits of the tab key to get from one field to the next.
This is due to the extra keyboard-focusable elements in the paste manager and tooltip modules.
Solution: add `tabindex="-1"` to these elements so they are skipped when tabbing through the page.
This also solves numerous problems with screenreaders not automatically reading down the page.
=> Improve keyboard accessibility for multiple Quill instances

config/grunt/dist.coffee, src/modules/keyboard.coffee, test/unit/modules/keyboard.coffee
Takes a string, number, or hotkey object, returns the handler function.
=> Add removeHotkey to keyboard module, closes #110

src/core/selection.coffee, src/modules/keyboard.coffee, src/modules/paste-manager.coffee, test/unit/core/selection.coffee
This fixes issue #433. When the user pastes or presses enter/backspace/delete, the browser's default scrolling behavior is prevented. (See src/lib/dom.coffee:142-143.) I wrote a function that scrolls the cursor into view and added it to the enter/deletion/paste event handlers.
=> Scrolls if cursor not visible after enter/deletion/paste

src/core/normalizer.coffee
Fixes https://github.com/quilljs/quill/issues/306
=> Preserve bold text when pasted

src/modules/keyboard.coffee
@jhchen I'm not sure if this is a bug or intentional (so haven't done a test) ... but when backspacing on a list item, it would behave correctly in the client (removing the format) but it wouldn't be classed as a user change, so when filtering out API text changes it can't be transmitted to other clients.
=> Backspacing on a list item

src/modules/multi-cursor.coffee
For some reason, my application generates errors like this:
```
TypeError: Cannot set property 'index' of undefined
at MultiCursor.moveCursor(~/quill/src/modules/multi-cursor.coffee:32:4)
at ?(~/quill/src/modules/multi-cursor.coffee:58:11)
at ?(~/lodash/index.js:1807:36)
```
I'd rather `moveCursor` just be a no-op in that case.
=> Don't throw an error when moveCursor() is called with an invalid userId

src/blots/block.js
This would result in errors because of inconsistencies with the return type of this method.
=> Return DOM object consistently with findNode

package.json
Upgrading ts-loader to ~0.7.2 fixes the webpack errors mentioned in https://github.com/quilljs/quill/pull/555
=> Upgrade ts-loader to ~0.7.2

package.json
A couple of webpack loaders were missing which prevented npm run build from running on a clean clone
=> Added missing dev dependencies required to build quill.js

modules/toolbar.js
=> Fixing Toolbar active state check

modules/keyboard.js, themes/base.js
This fixes a bug where if you use quill with Arrays have have additional prototyped properties, the iterator loops over those keys and breaks the property lookup. 
Also small reference issue.
=> Fixing a few bugs, reference error and Array prototype iteration

modules/clipboard.js
Added support for rich cut/copy and paste of delta json within quill editors. This allows for cool things like copying and pasting of embeds within and between quill editors.
=> Rich Clipboard Support

modules/toolbar.js
undefined is treated as a normal toggle, not as a disabler which is what is intended here
=> classlist.toggle needs to be passed false for falsy values

core/quill.js
This adds a static getModules() function to augment the instance getModules() function. Static getModules will give you access to all of the modules registered with quill while the instance getModules() function will return the modules loaded for that instance of quill.
=> Adding static getModules()

modules/clipboard.js
Here's a proposal and implementation for customizing interpretation of pasted HTML. This centers around a matcher functions with the signature:
function(Node, Delta): Delta;
The Delta parameter is the representation of the corresponding DOM node's children. A matcher function is to return the Delta representation of the corresponding DOM node and its children. Thus the matcher function simply adds what the DOM node represents, using the provided representation of its children. It also only needs to add one part of what it represents, as other matchers will be called to fill in the rest. It may also just return the given delta, if the corresponding node add no new information.
The way to customize pasted HTML interpretation is to add custom matcher through Clipboard's `addMatcher` which …
=> Clipboard API

blots/scroll.js
If an embed is the first item in quill, and you insert text before it, it'll end up getting inserted at the root by accident. This guards against that by wrapping any non-line blocks before line blocks in a block blot.
=> Fix an issue where we sometimes inserted a non line before a line

modules/keyboard.js
Adds a check to the keyboard event dispatcher to see if a handler in the list had previously called evt.preventDefault(). Useful if you add a keyboard handler yourself that overrides the default quill behavior for something.
=> test for added handlers calling preventDefault()

assets/core.styl
Fixes an issue where clicking the placeholder text on a Quill instance won't focus on that instance in Firefox, as described in issue #656.
Pointer-events fit within the browser support scope of Quill. Source: [caniuse.com](http://caniuse.com/#feat=pointer-events)
=> Fixes #656

formats/indent.js, modules/toolbar.js
Resolves #681 
Current version of quill 1.0 beta demonstrating problem: http://codepen.io/jonnolen/pen/GZaaaX
Version of quill 1.0 beta built with changes demonstrating problem resolved: http://codepen.io/jonnolen/pen/XdLaGO
=> fixes issue #681 with pasteHtml incorrectly re-hydrating tabs.

core/quill.js
Added a blur() convenience method for blurring/removing focus from editor. More obvious API call than calling setSelection(null).
Addresses https://github.com/quilljs/quill/issues/701
=> added blur() convenience method for blurring editor

themes/base.js
YouTube ID can have the following characters [a-zA-Z0-9_-]
\w is missing dash
=> Include dash in the YouTube regex

modules/formula.js
Causes a 'not-defined' error when Quill is **not** added as a global object.
=> Added missing import-statement in modules/formula

modules/clipboard.js
The types variable is unused after commit
https://github.com/quilljs/quill/commit/0c903eb890aecbe168931d45e4c358f420af6ae9
=> Remove unused types variable

core/quill.js, ui/tooltip.js
fix https://github.com/quilljs/quill/issues/938
=> Set the tooltip bounds container to document.body if undefined

docs/docs/api/events.md
The example was using the old text-change API from 0.2
=> fix selection-change example in API docs

formats/align.js, formats/direction.js, modules/clipboard.js, quill.js
LibreOffice and GMail use align and direction attributes.
fix https://github.com/quilljs/quill/issues/912
=> handle align and direction attributes on paste

docs/guides/how-to-customize-quill.md
Fix typo ("Otherweis" -> "Otherwise")
=> Fix typo in how-to-customize-quill.md

docs/docs/modules/clipboard.md
The method `dangerouslyPasteHTML` does not exists on `quill` itself, its part of the clipboard.
=> Fix documentation

ui/icons.js
=> Add missing icon for `code` format

.github/DEVELOPMENT.md
Noticed this while developing locally. Custom named npm scripts need to be called with `npm run`.
=> Correct npm script usage in DEVELOPMENT.md

package.json
This pull requests bumps the version of the parchment dependency to 1.0.2 rather than 1.0.1. This is to fix #1041. More information can be found here: https://github.com/yarnpkg/yarn/issues/812#issuecomment-253190930
=> Fix #1041 - version bump for parchment

docs/guides/designing-the-delta-format.md
Improving readability and adjusting some typos.
I've had soooooo much fun learning about Deltas! Thank you. Truly mindblowing.
=> Minor stylistic changes

docs/docs/download.md, docs/docs/quickstart.md, docs/docs/themes.md
"If this attribute [type] is absent, the script is treated as JavaScript."
Source: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script
=> Remove unnecessary type attribute in documentation

themes/base.js
reference: 
[chrome 52 slow](http://stackoverflow.com/questions/39187857/inputfile-accept-image-open-dialog-so-slow-with-chrome)
[input type MIME type](https://www.sitepoint.com/web-foundations/mime-types-complete-list/)
=> fix chrome 52+ input file label open slow

core/quill.js
I came across this when attempting to use ShareDB to synchronize two Quill clients on a document that consists entirely of a CodeBlock. But the missing check looks pretty obvious. I think the old CoffeeScript implementation of Quill actually had this check.
=> Only query the last op's insertion string if it's actually an insert

.github/DEVELOPMENT.md
Just missing the `run` parameter before the script name.
=> Update DEVELOPMENT.md with correct npm command

modules/keyboard.js
This fixes #1256 by not running the normal keyboard handler code if the list format is not enabled
=> Fixes #1256 Don’t create a list when list format is disabled

docs/docs/modules/keyboard.md
Tiny correction of the documentation.
=> Add missed word in keyboard.md

modules/keyboard.js
This prevents the cursor from jumping around when hitting `CMD+<delete>` in an empty editor. I'm happy to make any necessary changes.
Tested on macOS:
- Safari 10.0.3
- Chrome 56.0.2924.87
- Firefox 51.0.1 
Tested on Windows 10 (Browserstack):
- Edge 14
Fixes #1319
=> Prevent cursor from jumping around on backspace in empty editor

package.json
In version 2.1.1, CloneJS improved support for Internet Explorer. See this pull request for details: https://github.com/pvorb/clone/pull/77
From my limited testing so far, the fixes in CloneJS should enable QuillJS to run on a wider variety of Windows + Internet Explorer systems. For example, I've seen the dependency update fix some crashes of QuillJS on Internet Explorer 10 running on Windows Server 2012 R2.
If you're interested in merging this pull request, we should add some more Windows + Internet Explorer systems to the Saucelabs test matrix for QuillJS and see if we can increase support. Is this something that you'd be interested in doing?
=> Update clone dependency to >=2.1.1 <2.2

modules/clipboard.js
According to the CSS spec:
The keyword 'normal' is synonymous with '400', and 'bold' is synonymous with '700'.
https://www.w3.org/TR/CSS2/fonts.html#font-boldness
Fixes https://github.com/quilljs/quill/issues/1456
=> fontWeight '700' is synonymous with 'bold'

test/unit.js, test/unit/theme/base/tooltip.js, themes/base.js
This allows to convert m.youtube.com and www.youtube.com to embedded url (i.e., `www.youtube.com/embed/${videoId}`
Finishes work of #1155
=> fix(tooltip): adds detection for mobile youtube video

ui/picker.js
https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement
The Option element exposes a "selected" getter that works even when the "selected" attribute is not set, such as when the element is created by React.
Another way to do this is to provide an alternate data attribute to identify the default.
Codepen link demonstrating what happens when an initial "selected" attribute is not present on any of custom option tags for ql-align: https://codepen.io/alexkrolick/pen/qjMrEN?editors=0010
Fixes zenoamaro/react-quill#226.
=> use DOM API instead of attribute for "selected" option in dropdowns

docs/guides/cloning-medium-with-parchment.md
Hi there!
Only getting started with Quill but already in love :heart: 
There's a tiny error in the "Cloning Medium with Parchment" guide. The first sentence under the Final Polish section reads:
> With Parchment, we **able** able to add bold ...
And it should probably be:
> With Parchment, we **are** able to add bold ...
:)
=> Fix: Replace word in "Cloning Medium with Parchment" guide

docs/docs/api/contents.md
Replace "returing" with "returning".
=> Fix typo in docs/api/#contents

modules/keyboard.js, test/unit/modules/keyboard.js
Implements issue #1091.
Here is a simple gist demonstrating the value of this change:
https://gist.github.com/mattpalermo/e6db6ac3abdd85438f9555fba258551c
This is a breaking change so maybe it should go in a new experimental branch
until a major version bump is due.
Changes the Keyboard module to make use of the KeyboardEvent.key
event property rather than the now obsolete KeyboardEvent.keyCode
property. This has several advantages and is discussed in issue
1091.
THIS CHANGE IS A BREAKING CHANGE.
no attempt has been made to maintain backwards compatibility.
Existing unit tests have been modified to reflect the new behaviour
and pass. The functional test required no modification to pass.
Perhaps some more tests should be written to express the new
possibilities afforded by this change. For …
=> Use KeyboardEvent.key instead of .keyCode

blots/scroll.js, core/selection.js
Currently, I cannot insert any objects into the EMbeds which are handled by the global JS listeners:
For example: 
bootstrap dropdowns or any other plugins.
Also removes unused imported variable
=> Remove unused variable and event propagation from embeds

formats/list.js
This commit adds a ontouchstart handler to the checkbox format to allow checking and unchecking on a mobile device while focused on editor.
Based on comment by @sferoze on [this issue]([url](https://github.com/quilljs/quill/issues/759#issuecomment-328303747)).
=> Add ontouchstart handler for checkbox.

formats/list.js
Add touchstart listener if touchstart event is supported else add click listener. but do not add both.
=> Add touchstart listener if touchstart event is supported else add click listener. but do not add both.

modules/formula.js
* Use KaTeX's built in error reporting instead of throwing an exception and logging to the console.
* For #1737 
I ran into one issue and I'm not sure what standard procedure is to address since is not directly a part of this proposed change. [These lines](https://github.com/quilljs/quill/blob/develop/blots/embed.js#L12-L14) in `EmbedBlot` are throwing an error when I insert any formula, valid or invalid. I took look at git blame and found that `this.contentNode` was introduced in the last two weeks, but `this` is `undefined` because the function has a different context than the constructor. If that function is changed to an arrow function or `.bind(this)` is added to the end, that fixes the issue.
=> show error when parsing with KaTeX

docs/guides/building-a-custom-module.md
Just a small thing I thought about while reading the guides. This suggests a better / safer style.
=> Use innerText instead of innerHTML in guides

modules/keyboard.js
Taking on https://github.com/quilljs/quill/issues/1808, treating `*` the same as `-` to trigger a bullet list quicker than going through the toolbar.
=> Treat as * as another trigger for bullet lists

docs/docs/modules/clipboard.md
This commit updates the syntax used to annotate parameter types in the clipboard method documentation to match the rest of the docs.
=> Fix type annotation syntax in clipboard documentation

modules/history.js
This is a fix for #1376 **undo the first time,but the history.stack.redo.length = 0?**
The destination stack is currently updated after any `editor-change` events. This makes it hard to e.g. reactively enable/disable undo redo buttons. With this change, the stack is updated first, and the quill contents and selection is updated after, ensuring that the stack is up to date when any events are fired.
=> Fix for #1376. Up to date history stack on 'editor change'

test/unit/ui/picker.js, ui/picker.js
I work at LinkedIn, and we recently ran into some accessibility issues with the Quill picker concerning tabbing and ARIA attributes.
In our own LinkedIn picker (that extends the Quill picker), I've implemented the following changes to make the picker accessible, so I figured I'd put a pull request here too in case Quill developers were interested in benefitting from these accessibility changes.
Previously, the Quill picker was not a part of the tab order, which makes the picker inaccessible to screen readers/keyboard only users.
Furthermore, once the picker was added to the tab order, I found that the picker options were not tabbable. So, I made the option items tabbable and also added functionality to be able to select option items via use of the "Enter" key. I also made the dropdown …
=> Ensuring Quill picker is fully accessible

docs/docs/modules/keyboard.md
I noticed that the documentation for the [keyboard module] was a little inaccurate w.r.t. the format of config passed to quill at init (the `context` sub-object is not unwrapped as expected). I've amended the example code, and added a few sentences describing the expected config object format.
=> Improve keyboard docs

docs/docs/api/contents.md
remove invalid closing parenthesis `}` in docs/contents.md on line 171.
=> Invalid `}` on line 171 in api/contents.md

docs/guides/cloning-medium-with-parchment.md
If you actually look at the result of `getContents()` at the codepen example for adding the VideoBlot, you'll see that there is no src key within the video, it's just a string. This makes the code block that is supposed to be the outputted delta match what it's expected to be on Codepen.
=> Corrected delta displayed in video code block in Medium clone guide

modules/clipboard.js, test/unit/modules/clipboard.js
Fix for [#2224](https://github.com/quilljs/quill/issues/2224)
DOMParser will safely parse html without executing scripts or inline javascript handlers.  It will also automatically put script tags in the head of the document which we should be able to safely ignore. 
This implementation does change the resulting delta of the paste by not the script content as text.
Issue [#2224](https://github.com/quilljs/quill/issues/2224) identifies another issue where inline event handlers can execute javascript from non script tags.  I was unable to create a failing test with an `img.onerror` handler defined even though the failed img src request can be seen in the test report.  I can continue to work on this if necessary.  Here is the test:
```js
it('does not execute javascript', function() { …
```
=> Use DOMParser to safely parse html without script execution

modules/clipboard.js, test/unit/modules/clipboard.js
Fix for [#2222](https://github.com/quilljs/quill/issues/2222)
This fix only delegates responsibility to uploader if there is no rich text in clipboardData.
=> bypass uploader if clipboardData has rich text

core/editor.js, core/quill.js, test/unit/core/quill.js
This PR fixes issue #746 for real this time, adds tests, and also handles a wider variety of cases.  Fast-diff's cursor-position hint is no longer used; instead, the editor looks at both the old and new selection (cursor or range) to determine the best delta to represent the change.
There are many examples of ambiguous diffs that can only be disambiguated using selection information.  For example, the minimal insertion in `aaa` to `aaaa` could be at index 0, 1, 2, or 3.  The same is true for the two-character insertion in `bob` to `bobob`, or the single-character deletion in `aaaa` to `aaa`.  Because of backwards deletion (control-D or fn-delete on a Mac), both the old and new cursor are needed to get the delta right.  In order to handle the case where `foo` is selected and the letter `f` …
=> Generate more accurate deltas from typing

blots/block.js, modules/syntax.js
Fixes #2178.
While it feels a bit odd to make a function called `bubbleFormats` always exclude a particular format from its result, this function could really be called something like `collectFormatsForDelta`; it is only called to get the formats for a delta (or the public Quill API, `quill.getFormat()`).
It follows (I believe) that SyntaxCodeBlock no longer needs a custom `delta()` method.
=> Prevent code-token attribute in deltas

core/editor.js, test/unit/core/editor.js
=> fix insert text before block embed

modules/keyboard.js
When typing enter on an empty list line, it removes the list formatting and the indent (if there is one). This PR updates the behavior to emit a single change that removes both the list and indent formats rather than two distinct changes.
=> Emit single change when typing enter on empty list line

.github/DEVELOPMENT.md
Hi, I noticed this link leads 404 page and fixed it.
=> Fix invalid URL on the documentation

blots/cursor.js, core/selection.js, test/functional/epic.js
This PR refixes issue #1019 and de0d564c7e69ee2e1cc3831d6b94ae1fbe8d2e5b.
Repros for bugs addressed:
1. The repro in #1019
2. Type `aa`, click between the two A's, then do command-B, command-B, then type `b`.  You should get a plain `aba` with the cursor after the `b`.  Added a functional test for this.
3.  Type `aa`, click between the two A's, then do command-B, type `b`, command-B, type `c`.  You should get `abca` with a bold `b`.  Added a functional test for a case similar to this.
4.  Type a string of text (e.g. `asdfasdf`), click in the middle of it, then do command-B, command-B, and then click somewhere else in the text, before or after the first position.  The text cursor should stay where you planted it (instead of e.g. jumping to the end of the line).  This is equivalent to the …
=> Fix Cursor blot restoration and selection preservation

themes/snow.js
Fixes #2438
The link has the target attribute set to _blank but has no rel property. This means that documents containing untrusted links make the page they are embedded in susceptible to tabnabbing https://www.owasp.org/index.php/Reverse_Tabnabbing.
This PR sets the rel property to noopener (also norefferer and nofollow)
=> Fix tabnabbing vulnerability in Snow theme

.github/DEVELOPMENT.md
Hello! I've been using Quill for about two years now, and I'd like to start contributing back. This is my first PR on the project.
I found it super easy to set up the development environment and get up and running. During the process, I found it difficult to figure out where to go once `npm start` was run - so I added this table of links.
Please let me know if any of those table entries are incorrect and/or if I'm missing anything that should be there! :-)
=> Add link table to dev setup guide

core/editor.js, test/unit/core/editor.js
At the moment, it's possible to construct a "mixed" list of ordered and
bulleted items, eg:
```markdown
1. One
2. Two
- Foo
- Bar
```
If you create this list in Quill, then cut it and paste it back again,
the bullet items are transformed into ordered items, which is
surprising.
This change updates the list HTML conversion logic to check that the
list is still a continuation of the previous type. If not, it starts a
new list of the correct type.
=> Correctly convert mixed lists

blots/scroll.js, core/quill.js, test/unit/blots/scroll.js
At the moment, consumers cannot enable drag events within the editor,
because they're all disabled by the `Quill` constructor registering an
anonymous `dragstart` handler.
This change allows consumers to override this behaviour by moving this
listener to the `Scroll` blot, where the `dragstart` is prevented in a
named method, which can be overridden by extending the class.
=> Move drag blocking to `Scroll`

modules/clipboard.js
fixing this: CSS style text-decoration: underline and text-decoration: line-through should be converted
into HTML tags u and s
=> fix for https://github.com/quilljs/quill/issues/2585

formats/link.js, test/unit/formats/link.js
* Add attribute rel="noopener noreferrer" to <a> tags created by formats/link.js
* Make unit tests for links expect rel attribute
The vulnerability described in #2438 was not fully fixed with PR #2439 .
Using quill in readonly mode to display content still results in vulnerable anchor tags, because
the create function in formats/link.js sets target="_blank" but not rel="noopener noreferrer".
This pull request in combination with #2439 mitigates the tab nabbing vulnerability.
=> Fix tab nabbing vulnerability in formatted links

core/quill.js
Hi all!
Since Grammarly now works well on Quill in all browsers, we no longer need to block it.
This PR unblocks Grammarly from integrating on Quill.
=> Unblocks Grammarly

docs/1.0/docs/api/contents.md, docs/docs/api/contents.md
There is a small typo in docs/1.0/docs/api/contents.md, docs/docs/api/contents.md.
Should read `returning` rather than `returing`.
=> docs: Fix simple typo, returing -> returning

modules/keyboard.js
Currently, press backspace at the beginning of a header clears the header format even if the previous line is empty.
1. In an empty editor, press the enter key to create a new line.
2. Enter some text and set the line as a header.
3. Place the cursor at the beginning of the line.
4. Press backspace.
The header format is lost.
The header format should be kept. In contrast, if the previous line is not empty (either it has content or it is set a block format like `{ header: 2 }`).
---
Follow the reproduce steps, make sure the result is what mentioned in the expected section above.
=> Backspace at the header beginning should keep the format

formats/code.js, modules/syntax.js, test/unit/core/editor.js, test/unit/modules/syntax.js
`CodeBlockContainer#html()` generates duplicated `\n` when deals with empty lines. See the test plan for reproduction steps.
This PR added a fix for that, also fixed a related issue that copying & pasting code block doesn't keep the highlighting language.
1. Run `npm start`
2. Visit `http://localhost:9000/standalone/full/`
3. Copy the following code block to the editor:
```javascript
start
end
```
4. Add some plain text after the code block. See the screenshot below.
5. Copy the code block in the editor and paste after the plain text.
6. Make sure the pasted code block has the same content as the original one.
7. Set a highlighting language after step 3 and try again. Make sure the pasted code block keeps the language setting.
=> Fix length mismatch when copying code

modules/clipboard.js, test/unit/modules/clipboard.js
**To reproduce:**
1. Run `npm start` and open http://localhost:9000/standalone/full/
2. Add `<button class="ql-list" value="unchecked"></button>` to full.html so we can have a button to set list style to unchecked.
3. Use the button to create a checklist with some nested items.
4. Copy & paste the whole list.
**Expected:**
The indentation should be preserved.
**Actual:**
The indentation is lost.
-----
**Test Plan**
Follow the reproducible steps above, make sure it works as expected.
=> Fix pasting in checklist does not preserve indentation

assets/core.styl
Currently, blocks (except p and headings) reset inner lists' numbers, which is caused by `counter-reset`. The intention was to use `counter-reset` to reset number values to 0 but there's a side effect that can create a new counter.
This change uses `counter-set` instead to avoid the side effect.
Test plan:
In supported browsers, make sure the list number shows correctly as the following screenshot:
In other browsers, the numbers should not change.
=> Keep list numbers continuous when separated by certain elements

modules/history.js
Currently, our editor listens on the common hotkeys (cmd+z / cmd+shift+z) for undo/redo but the user could always undo using native browser UI like right-click, the edit topbar menu, and on mobile iOS there is a toolbar, and the native undo usually does not do the right thing.
Most modern browsers support using `beforeinput` to interrupt native undo/redo inputs so we'll use this to handle them natively. Firefox supports this event since v74 but hasn't enabled it by default.
To test:
* Insert some text, make some chars bold.
* Click Undo in the context menu, make sure the chars are unbold. Click undo again should remove the text.
* For Firefox, it should behave the same as before.
=> Handle native undo/redo

blots/scroll.js
Closes #1847
Previously, mutations generated inside nested Quill instances will be also handled by the parent, which is not expected.
This PR checks whether the scrolls of the blots are the current one and will ignore them if that isn't the case.
=> Ignore mutations happens in nested Quill instance

assets/core.styl
Reproducible steps:
1. Add some list items and a paragraph like the attached screenshot.
2. The second list should start with 1 but in Firefox it starts with 3.
The reason is Firefox changes its counter behavior recently: https://bugzilla.mozilla.org/show_bug.cgi?id=1679712. We are using `counter-reset` to set the numbering to 0. However, in Firefox, it actually creates a new counter instead of reset the existing one.
To fix, the PR uses `counter-set`, and if it's not supported fallback to `counter-reset`.
Browser behaviors for reference:
|               | Chrome              | Firefox             | Safari              |
|---------------|---------------------|---------------------|---------------------|
| counter-reset | CSS level 2 | CSS level 3 | CSS level 2 |
| counter-set   | ✅ …
=> Header/paragraph doesn't reset list numbering in Firefox

modules/clipboard.js, modules/keyboard.js, test/unit/modules/clipboard.js
To test:
1. Open http://localhost:9000/standalone/full/
2. Create two lines:
```
Hea|der
Normal |paragraph
```
3. Cut text between two |.
Expected:
The first line is a header.
Actually:
The first line is a normal paragraph.
=> Cut across lines shouldn't affect the formatting of the line above

assets/core.styl
The cause is items with `display: contents` [don't have correct frames](https://bugzilla.mozilla.org/show_bug.cgi?id=1131128) on Firefox, so the event listener attached to the checkbox won't work.
This PR only applies the `display: contents` to ordered and bullet list. It worth noticing that `display: contents` was introduced to fix the following issues:
1. On Firefox, command + left arrow key can't move the caret to the beginning of the list item.
2. Left arrow can't move the caret that is at the beginning of a list item to the previous line.
After this change, regressions of the above issues are expected but only for the checkboxes.
Also, after some tests, `display: contents` introduces a side effect on Safari that pressing command + left arrow on the first line of a list item will move …
=> Fix checkbox not checkable on Firefox

core/editor.js, test/unit/core/editor.js
- Use same approach as #2278 to consume next new line when inserting inline embed before a block embed to ensure index calculations for the delete are not off by one due to implicit newline being added
This fix requires the delta to explicitly specify the implicit newline that gets added as part of the new block container that the inline embed is created inside. If not explicitly specified, the internal index tracking will be off by one and the delete will consume the implicit newline instead. (which is the current behaviour)
=> Fix insert inline embed with delete before block embed

modules/keyboard.js
It's more intuitive to not preserve inline formats on enter.
=> Discontinue inline formats on enter

blots/scroll.js, core/quill.js, test/unit/core/selection.js
Previously, `Quill#getLeaf()` can return non-leaf blots, which is unexpected. For example, it breaks `Selection#getBounds()` as it calls `leaf.position(offset, true)`, which is only provided by leaf blots.
The reason `Quill#getLeaf()` may return a non-leaf blot is, in `ParentBlot#path()`, if `this.children.find(index, inclusive)` return `[null, 0]` (aka the parent blot is empty), the last element of the path would be the parent blot itself, causing `Scroll#leaf()` gets the parent blot.
The reason that a parent blot can be empty is in `Container#optimize()`, [we don't call](https://github.com/quilljs/parchment/blob/4257051dfc0a9c3e240c4906f8e36a697f95b1f8/src/blot/abstract/container.ts#L40) container's children's `optimize()` function, so the children who are parent blots don't have a …
=> getLeaf() should ignore non-leaf blots

core/selection.js
This PR fixes the exception of `Error: Failed to execute 'setStart' on 'Range': The offset 4294967295 is larger than the node's length`.
It happens when the `Text` node is empty, which is possibly caused by the `Container#optimize()` issue mentioned in https://github.com/quilljs/quill/pull/3489.
=> Fix getBounds of empty text nodes

formats/code.js, modules/syntax.js
The `code()` method should be rendering target agnostic so this PR moves the encode logic to `html()`. It breaks BC for `code()` but it was introduced in 2.0 and we don't have it documented or decided to make it as a public API yet so should be fine.
=> Move code escaping to `html()`

blots/cursor.js, modules/clipboard.js, test/unit/core/selection.js
When `.ql-cursor` is inside a link, and the user types a character, Safari will [push down the link](https://github.com/WebKit/WebKit/blob/04b6d7ece074eeb461d3e222d468ef0836256191/Source/WebCore/editing/CompositeEditCommand.cpp#L1706) inside `.ql-cursor` and move the cursor's `textNode` inside the link. This breaks our position calculation. So this PR makes sure the cursor is always unlinked to avoid this.
To test:
1. Type "abc", bold them and linkify them.
2. Move the caret after "c", press cmd+b to cancel the bold format.
3. Type any characters, and delete some characters, make sure everything works as expected.
=> Keep cursor unlinked to avoid elements being pushed down inside

core/selection.js
On Blink, `document.getSelection()` [forces](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/editing/dom_selection.cc;l=207) [layout](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/editing/frame_selection.cc;l=159-160;drc=dc3638e64423b1d2d5e3323b419028ab631f3923) which breaks the browser's optimization of batch DOM mutations. The impact on the performance is noticeable when you do a lot of DOM mutations and `getRange()` at the same time. It is worth noticing that editor mutation triggers `getRange()` (https://github.com/quilljs/quill/blob/d462f8000ffbaa3aab853809fb08f7809f828475/core/quill.js#L103) so the impact is non-trivial when you initialize many Quill instances at the same time.
This PR optimizes …
=> Avoid fetching selections when possible

core/quill.js
It's only necessary to call `setContents()` when `html` is not empty. Otherwise, we can avoid it for better performance.
=> No need to setContents when container is empty

modules/keyboard.js
Until this change, the Tab key always indented selected lines. However, it's more common for code editors to insert tab char with collapsed selection.
To test:
1. When the selection is collapsed, Tab should insert `CodeBlock.TAB`.
2. With the shift key pressed, Tab should always reduce indention.
3. Otherwise it should keep the current behavior.
=> Improve Tab handling in code block

.gitignore, .npmignore, package.json, tsconfig.json
This PR reverts https://github.com/quilljs/quill/pull/3631/commits/1f484a20e1a61a6929ec2c2e9595c21e6e3a388a to improve the compatibility with TypeScript by moving from `exports`.
TypeScript 4.7 supported `exports` but it requires `moduleResolution` set to `Node16`. This leads to some side effects like relative imports have to include the extename (`import('../a.js')` instead of `import('../a')`), and most importantly `Node16` is not designed to be used together with bundlers in browser environments, as its name suggests and it brings some Node.js-specific requirements and behaviors.
TypeScript 4.9 may provide some `moduleResolution` modes that can support `exports` without introducing any Node.js-specific behaviors: https://github.com/microsoft/TypeScript/issues/50152. However, at best it …
=> TypeScript compatibility improvement

modules/clipboard.ts
`matchers` of `ClipboardOptions` is missing the `Selector` part.
Test plan: make sure all tests pass.
=> Fix clipboard typing

core/instances.ts
Previously `Quill.find()` returned `any`, whereas it should be `Quill | Blot`.
=> Add missing typing for Quill.find

website/content/guides/comparison-with-other-rich-text-editors.mdx
=> Fix typo in comparison-with-other-rich-text-editors.md

formats/link.ts
SMS protocol was missing added to `PROTOCOL_WHITELIST`
SMS links are widely supported - https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/SMSLinks/SMSLinks.html
=> Add SMS to link protocol whitelist

core/quill.ts, core/selection.ts
<del>Breaking Change: This PR moves scrollIntoView from selection to quill to make it easier to be overridden. The only reason `scrollIntoView` was in selection seems to be the usage of `lastRange` but in quill we already use `this.selection.lastRange`.</del> On second thought I think semantically it makes sense to keep it in the selection module.
Also not sure why `if (first == null || last == null) return;` is needed so this PR removes it.
=> Refactor Selection#scrollIntoView()

modules/keyboard.ts, package-lock.json, package.json
This lets us remove the `@ts-expect-error` comments from the `Keyboard` module.
=> 🏷️ Add `@types/lodash.clonedeep` types

modules/toolbar.ts
Handlers are called with a format-dependent [`value`][1].
This change updates the `Handler` type to allow passing a value.
[1]: https://github.com/quilljs/quill/blob/d2f689fb4744cdada96c632a8bccf6d476932d7b/modules/toolbar.ts#L106
=> 🏷️ Fix Toolbar `Handler` type

core/quill.ts
Quill allows to pass a string as the DOM selector for the container. That is actually the only documented way to do it (https://quilljs.com/docs/quickstart/), and it works, but it's not typed.
=> 🐛 Allow string selector for container

package-lock.json, package.json
quill-delta@5.1.0 adds semantic cleanups to `Delta#diff()`, which means in general it would generate better diff results especially when the two text varies greatly.
=> Upgrade quill-delta for semantic cleanups

core/editor.ts, test/unit/core/editor.js
Closes #3620
There are two cases where an implicit newline char (`\n`) could be added:
1. When you insert an inline embed op or text op that doesn't end with "\n" to the end of the document (after the last `\n`) or right before a block embed, an implicit `\n` will be appended to that op.
2. When you insert a block embed after an inline embed op or a text that doesn't end with `\n`, an implicit `\n` will be prepended to the op.
Before this PR, we only tracked the first case with a flag `addedNewline`. When it's true, we increase the index by 1 and record it in `deleteDelta` to delete it. The reason we want to delete it instead of skipping it is that a following op may contain a `\n`, which makes the implicit `\n` redundant.
However, we didn't catch the second case which led to #3620. This …
=> Fix applyDelta with block embed

core/editor.ts, test/unit/core/editor.js
Closes #3623
Similar to how we revert the formats for text, we get the current inline formats of the target position and calculate the diff, and apply them to the inserted embed.
=> Fix embed inherits formats unexpectedly

core/quill.ts
`Quill.getText()` is allowed to be called with no arguments, since it [defaults][1] to returning the whole document.
However, the overload declarations require arguments, resulting in a compilation error when trying to call `getText()` with no arguments:
```
(method) Quill.getText(range: {
index: number;
length: number;
}): string (+1 overload)
Expected 1-2 arguments, but got 0.ts(2554)
```
This change makes all the arguments in the overloads optional to match the implementation.
[1]: https://github.com/quilljs/quill/blob/d2f689fb4744cdada96c632a8bccf6d476932d7b/core/quill.ts#L501-L502
=> 🏷️ Fix `Quill.getText()` arguments

blots/block.ts
The `Block` blot inherits from `parchment`'s `ParentBlot`, where the `ref` argument [is optional][1].
This change updates the `Block` signature to match its parent.
[1]: https://github.com/quilljs/parchment/blob/634e50f4d73a3351952250146510332dbc0af961/src/blot/abstract/parent.ts#L238
=> 🏷️ Fix `Block.moveChildren()` signature

core/quill.ts
`Quill.getFormat()` is allowed to be called with no arguments, since it [defaults][1] to just getting the current selection.
However, the overload declarations require arguments, resulting in a compilation error when trying to call `getFormat()` with no arguments:
```
(method) Quill.getFormat(index: number, length?: number): any (+1 overload)
Expected 1-2 arguments, but got 0.ts(2554)
```
This change makes all the arguments in the overloads optional to match the implementation.
[1]: https://github.com/quilljs/quill/blob/d2f689fb4744cdada96c632a8bccf6d476932d7b/core/quill.ts#L435
=> 🏷️ Fix `Quill.getFormat()` arguments

modules/clipboard.ts
`Clipboard.dangerouslyPasteHTML()` is allowed to be called without an index as its first argument.
At the moment, doing this results in a compilation error:
```
(method) Clipboard.dangerouslyPasteHTML(index: number, html: string, source?: EmitterSource): void
Expected 2-3 arguments, but got 1.ts(2554)
```
This change adds the overload to allow this.
=> 🏷️ Add overload for `Clipboard.dangerouslyPasteHTML()`

blots/block.ts, test/unit/blots/block-embed.js, test/unit/core/editor.js
`Block#insertAt()` handles the case where the text contains multiple `\n`s, whereas `BlockEmbed#insertAt()` doesn't. This PR makes the latter behave the same as `Block#insertAt()`.
=> Fix HTML and Delta not matching

blots/block.ts, blots/cursor.ts, blots/embed.ts, blots/scroll.ts, core/editor.ts, core/logger.ts, core/quill.ts, core/selection.ts, e2e/utils/index.ts, formats/table.ts, modules/clipboard.ts, modules/history.ts, modules/keyboard.ts, modules/syntax.ts, modules/table.ts, modules/tableEmbed.ts, modules/toolbar.ts, modules/uploader.ts, themes/base.ts, themes/bubble.ts, themes/snow.ts, tsconfig.json, ui/icon-picker.ts, ui/picker.ts
We enable `strictNullChecks` to enable type safety and also make method return types include `null` values. Before this PR, methods like `() => document.getElementById('myid')` will have a return type of `Element` instead of `Element | null`.
This PR doesn't try to fix all typing errors for simplicity, instead, it fixed some of them, especially ones related to return types.
=> Enable strictNullChecks

core/editor.ts, test/unit/core/editor.js
This PR fixed two bugs related to inserting inline embeds caught by https://github.com/quilljs/quill/pull/3789. See test cases and comments for details.
=> Fix inline embed insertions with applyDelta()

core/editor.ts, test/unit/core/editor.js
Consider a document with a single piece of bold text. As a `Delta`, this
would be represented as:
```js
const doc = new Delta().insert('a', {bold: true})
```
Now consider the following `Delta` being applied:
```js
const delta = new Delta().insert('\n1')
```
The above `Delta` will:
- prepend the document with a newline
- follow that newline with an **unformatted** string
Indeed, using `doc.compose(delta)` yields:
```js
const result = new Delta()
.insert('\n1')
.insert('a', {bold: true})
```
However, the same result is not reached when using the Quill
`editor.applyDelta()`, which instead results in bold formatting being
incorrectly applied to our unformatted string:
```js
const badResult = new Delta()
.insert('\n')
.insert('1a', {bold: true})
```
This happens because Quill does an insert of …
=> 🐛 Fix inserting newlines into formatted text

core/editor.ts
At the moment we try to reassign `lines: Blot` and `leaves: Blot` to
`lines: {}` and `leaves: {}`.
This change just creates new variables, so that we don't have these compiler errors.
=> 🏷️ Fix TypeScript error

blots/block.ts, blots/cursor.ts, blots/scroll.ts, core/editor.ts, core/quill.ts, formats/bold.ts, formats/header.ts, formats/script.ts, formats/table.ts, modules/syntax.ts, modules/table.ts, package-lock.json, package.json, themes/snow.ts
Parchment added two changes regarding TypeScript typings:
1. (Breaking) Exposing all types from 'parchment' so consumers don't need to import from 'parchment/dist/*'
2. `Parchment#descendants(Blot)` now works and will narrow down return types.
=> Upgrade Parchment to fix typings

_develop/browsers.js, _develop/webpack.config.js, babel.config.js, package-lock.json, package.json, tsconfig.json
This makes building faster and TypeScript doesn't need to care about output format.
=> Use babel-loader for building

themes/base.ts
At the moment, since `@ts-expect-error` [doesn't apply][1] to type definitions, we get a downstream compilation error:
```
TS2416: Property 'addModule' in type 'BaseTheme' is not assignable to the same property in base type 'Theme'.
Type '(name: string) => unknown' is not assignable to type '{ (name: "clipboard"): Clipboard; (name: "keyboard"): Keyboard; (name: "uploader"): Uploader; (name: "history"): History; (name: "selection"): Selection; (name: string): unknown; }'.
Type '{}' is missing the following properties from type 'Clipboard': matchers, addMatcher, convert, convertHTML, and 8 more.
10     addModule(name: string): unknown;
```
This change updates the `Base` class to have the same signature as for `addModule()` as its parent class.
[1]: …
=> 🏷️ Fix `addModule()` types

themes/base.ts
At the moment, the `BaseTooltip.edit()` signature has type:
```ts
declare class BaseTooltip extends Tooltip {
edit(mode?: string, preview?: null): void;
}
```
This change tweaks the signature to be more accurate:
```ts
declare class BaseTooltip extends Tooltip {
edit(mode?: string, preview?: string | null): void;
}
```
=> 🏷️ Fix `BaseTooltip.edit()` signature

core/composition.ts, test/unit.js, test/unit/core/composition.js
This makes it possible to monkey-patch listener handlers before we come out an official way for core component overriding.
=> Refactor composition to allow overriding

blots/block.ts, blots/scroll.ts, core/editor.ts, core/quill.ts, test/fuzz/editor.test.ts, test/unit/blots/scroll.js, test/unit/core/editor.js
This PR improves `Quill#setContents` performance by using `insertBefore()` whenever possible.
=> Improve inserting performance

blots/scroll.ts, test/fuzz/editor.test.ts, test/unit/core/editor.js
`BlockEmbed#format()` requires `attributor`, which is only created when the blot is attached. This PR fixes the issue by attaching the blot before applying formats.
=> Fix block embed attributor errors

e2e/history.spec.ts, e2e/pageobjects/EditorPage.ts, modules/history.ts
Closes #509
We now record current selection range in history module so that when users perform undo/redo, we can restore the saved selection.
=> Record selection in history module

modules/toolbar.ts, test/unit/modules/toolbar.spec.ts
This adds `aria-pressed` attributes to Toolbar buttons. The attribute value set consistently with `ql-active` presence or absence.
Ref #2038
=> Toolbar: add aria-pressed to toolbar buttons

core/editor.ts, test/unit/core/editor.spec.ts
=> getHTML() should include outer tag when range is entire line

assets/bubble.styl
The link styling for the bubble theme broke the tooltip close styling (making it invisible).
Broken:
Fixed:
=> fix styling for bubble tooltip close

modules/toolbar.ts, test/unit/modules/toolbar.spec.ts, ui/picker.ts
Closes #1173, #3639
This PR added a basic support for aria labels. It's possible to customize it (e.g. for i18n support) by [passing a HTML container instead as documented](https://quilljs.com/docs/modules/toolbar/#:~:text=For%20use%20cases%20requiring%20even%20more%20customization%2C%20you%20can%20manually%20create%20a%20toolbar%20in%20HTML%2C%20and%20pass%20the%20DOM%20element%20or%20selector%20into%20Quill.).
=> Add aria labels to toolbar

website/src/pages/index.jsx
The usage of `var` is generally considered obsolete and legacy. This makes the library look outdated in comparison with the competitors. As all of the modern browsers now support `const`. It makes Quill to look outdated especially on the front page example.
More context here: https://github.com/quilljs/quill/pull/3876
```npm run website:develop```
The front page example now uses `const`
This diff
- Updates front-page example to use `const` instead of `var`
=> Update landing page to use const instead of var in the example

website/content/docs/api.mdx, website/content/docs/configuration.mdx, website/content/docs/modules.mdx, website/content/docs/modules/clipboard.mdx, website/content/docs/modules/history.mdx, website/content/docs/modules/keyboard.mdx, website/content/docs/modules/syntax.mdx, website/content/docs/modules/toolbar.mdx, website/content/docs/quickstart.mdx, website/content/docs/themes.mdx, website/content/guides/cloning-medium-with-parchment.mdx, website/content/guides/designing-the-delta-format.mdx, website/content/guides/how-to-customize-quill.mdx, website/content/guides/upgrading-to-1-0.mdx, website/content/guides/why-quill.mdx
The usage of `var` is generally considered obsolete and legacy. This makes the library look outdated in comparison with the competitors. As all of the modern browsers now support `const`. It also matches the browser support that Quill targets. So I propose to update the documentation not to use outdated javascript anymore and switch to the modern constructs in the official documentation.
Updating landing page is in a separate pull request: https://github.com/quilljs/quill/pull/3877
[https://caniuse.com/?search=const ](https://caniuse.com/?search=const)
[Official supported browsers](https://github.com/quilljs/quill/#readme) 
Docs still work as expected:
This diff
- Updates all places in the documentation and guide sections to update `var` to `const`
- It keeps the `blogs` section as-is as …
=> Update docs and guides to use const vs var

assets/core.styl, core.ts, core/quill.ts, e2e/fixtures/Composition.ts, e2e/fixtures/index.ts, e2e/list.spec.ts, e2e/pageobjects/EditorPage.ts, e2e/replaceSelection.spec.ts, modules/uiNode.ts, test/unit/modules/toolbar.spec.ts
This PR added a new module to normalize browser's native behavior. 
Specifically, in Firefox, when the current line blot contains a UI node, pressing CMD+ArrowLeft in macOS would result in the caret being placed right before the UI node. This PR normalizes the behavior by checking such situations and moving the caret after the UI node.
* This PR fixed #3837 and also added an E2E test case.
* This PR fixed CMD+ArrowLeft not working in Firefox for checklists.
* Make sure no regressions for #3837
* Make sure CMD+ArrowLeft works in Firefox for all list types.
=> Normalize UI node selection

modules/uiNode.ts, test/unit/modules/uiNode.spec.ts
When multiple shortcuts are pressed, we should extend the deadline instead of just ignoring.
Test plan:
1. `npm start`
2. Open http://localhost:9000/standalone/full.
3. Add a list item.
4. Press CMD+ArrowRight twice quickly.
5. Press CMD+ArrowLeft.
6. Make sure the caret is placed at the start of the line.
=> Handle multiple navigation shortcuts

core/editor.ts, core/quill.ts, core/selection.ts, modules/keyboard.ts, package-lock.json, package.json, themes/base.ts, themes/bubble.ts, themes/snow.ts
By switching to lodash-es, we can save ~10KB minimized size for the 3 packages currently used (`cloneDeep`, `isEqual`, `merge`), because independent packages (`lodash.clonedeep` etc.)  each contain their own lodash sub-modules (`isObject`, `isArray`, etc.)
See [example](https://stackblitz.com/edit/vitejs-vite-dnhgzn?file=lodash-es.js&file=lodash-separate.js&terminal=dev) for build size comparison:
=> Refactor: switch to lodash-es

packages/website/content/guides/upgrading-to-1-0.mdx, packages/website/src/pages/playground.jsx
=> Fix docs typo

CHANGELOG.md, packages/quill/src/modules/clipboard.ts, packages/quill/test/unit/modules/clipboard.spec.ts
At the moment, if you paste the following HTML, the newline between the `<span>` elements is incorrectly discarded.
```html
<span>foo</span>
<span>bar</span>
```
This will currently insert `foobar` into Quill, when we'd expect `foo bar`, since newlines should [treated as spaces][1] between inline elements (such as `<span>`).
This change updates the `matchText()` clipboard matcher to check if the text node is between inline elements or not before early-returning.
[1]: https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace
=> Convert newlines between inline elements to a space

CHANGELOG.md, packages/quill/src/modules/clipboard.ts, packages/quill/test/unit/modules/clipboard.spec.ts
Closes https://github.com/quilljs/quill/issues/1434
This PR ensures that only registered formats can be applied.
=> Avoid generating unsupported formats on paste

CHANGELOG.md, packages/quill/src/modules/clipboard.ts, packages/quill/src/modules/normalizeExternalHTML/index.ts, packages/quill/src/modules/normalizeExternalHTML/normalizers/googleDocs.ts, packages/quill/src/modules/normalizeExternalHTML/normalizers/msWord.ts, packages/quill/test/unit/modules/clipboard.spec.ts, packages/quill/test/unit/modules/normalizeExternalHTML/normalizers/googleDocs.spec.ts, packages/quill/test/unit/modules/normalizeExternalHTML/normalizers/msWord.spec.ts
=> Improve support for pasting from Google Docs and Microsoft Word

CHANGELOG.md, packages/quill/src/modules/clipboard.ts, packages/quill/test/unit/modules/clipboard.spec.ts
=> Ignore whitespace between pasted empty paragraphs

packages/website/content/docs/modules/toolbar.mdx
Users often ask for a list of all available formats as array and HTML.
I suggest to also expand the HTML example with all available formats similar to the [formats page](https://v2.quilljs.com/docs/formats) (not in this PR)
Should we also add inline-code and check list?
```
'code'
{ 'list': 'check' }
```
=> Add link, image, video, formula to the formats array example

packages/quill/test/unit/core/selection.spec.ts
I'm not sure why the "large text" test passes, but we have derivative tests in our fork that fail because the `SizeClass` attributor is missing, and the `ql-size-large` class is stripped.
You can reproduce in this repo if you change the test setup:
```diff
test('large text', () => {
const { reference, container } = setup();
const selection = createSelection(
-  '<p><span class="ql-size-large">0000</span></p>',
+  '<p>0000</p>',
container,
);
+ selection.scroll.formatAt(0, 4, 'size', 'large');
const span = container.querySelector('span') as HTMLSpanElement;
const bounds = selection.getBounds(2);
expect(bounds?.left).approximately(
reference.left + span.offsetWidth / 2,
3,
);
expect(bounds?.height).approximately(span.offsetHeight, 3);
expect(bounds?.top).approximately(reference.top, 3);
}); …
```
=> Add missing attributor for `Selection` test

packages/quill/src/modules/toolbar.ts, packages/quill/test/unit/modules/toolbar.spec.ts
This change fixes the following bug:
1. Start with plain text "foo bar" in the editor
2. Highlight "bar" (NB: it's important to select text that's not at
the start)
3. Hit Ctrl+B to apply bold formatting
4. Notice that the bold button in the toolbar doesn't receive the
`ql-active` class, when it should
This appears to happen because the listener on `SCROLL_OPTIMIZE` gets an
incorrect range.
Instead of listening on optimize, we listen for all `EDITOR_CHANGE`
events, which _do_ get the correct range.
=> Fix toolbar button state not updated in some cases

CHANGELOG.md, packages/quill/src/modules/toolbar.ts, packages/quill/src/themes/bubble.ts, packages/quill/test/unit/core/selection.spec.ts, packages/quill/test/unit/modules/toolbar.spec.ts
Closes https://github.com/quilljs/quill/issues/4006
=> Merge from develop branch

CHANGELOG.md, packages/quill/src/core/selection.ts, packages/quill/test/unit/core/selection.spec.ts
Cherry-picked from #3774.
Closes #3774
At the moment there's a bug when trying to get the bounds of a range
which starts at the end of a text node at the end of a line.
In this case, the returned bounds span the entire width of the editor,
which isn't the desired result.
This change fixes the issue by checking if the Quill range starts at the
end of a leaf. If it does, we try to define the range starting at the
beginning of the next leaf instead.
=> 🐛 Fix Selection.getBounds() when starting range at end of text node

CHANGELOG.md, packages/quill/babel.config.js, packages/quill/package.json
For users installing from npm, they already have a bundler that can handle es modules.
For users that want to run quill in nodejs directly, it's currently not possible due to [side effects calling DOM](https://github.com/quilljs/quill/blob/cd3203f6f092af123b37cea629e76acb842d169f/packages/quill/src/core/emitter.ts#L8-L17)
By preserving modules, it allows third party dependencies (e.g. lodash-es) to be tree shaken. Currently lodash-es is fully bundled by users because of es modules transpiled to `require()` https://www.npmjs.com/package/quill/v/2.0.0-rc.1?activeTab=code
=> Preserve es modules in babel config

CHANGELOG.md, packages/quill/src/core/editor.ts, packages/quill/test/unit/core/editor.spec.ts
Fix https://github.com/quilljs/quill/issues/3957#issuecomment-1951057951
=> Fix getSemanticHTML for list items

packages/website/content/docs/delta.mdx
The example in the playground is using `contents` while displaying the changes in the playground.
=> Fix example for content and delta in playground

CHANGELOG.md, packages/quill/src/modules/clipboard.ts, packages/quill/test/unit/modules/clipboard.spec.ts
This PR brought back some old behaviors that would ignore empty `div`s when pasting from external sources. An example is when pasting from Office online, it contains the empty divs that are UI controls and should be ignored.
=> Fix redundant newlines when pasting from external sources

CHANGELOG.md, packages/quill/src/core/quill.ts, packages/quill/src/core/utils/createRegistryWithFormats.ts, packages/quill/test/unit/core/quill.spec.ts, packages/quill/test/unit/core/utils/createRegistryWithFormats.spec.ts, packages/website/content/docs/configuration.mdx
Achieve a similar purpose as `registry` option but it's easier to use. As in most cases users don't need to overload a format to have different implementations.
=> Add formats option for specifying allowed formats

CHANGELOG.md, package-lock.json, packages/quill/package.json, packages/quill/webpack.common.cjs
Previously, source maps for libraries are not included in Quill's bundle.
=> Include source maps for Parchment

CHANGELOG.md, packages/quill/src/modules/clipboard.ts
Quill v1 used `data-checked` attribute on the `ul` tag, whereas v2 has changed to `data-list` attribute on the `li` tags.
This change allows the matcher for list tags to recognize the v1 structure.  This will help in situations where any consumers have upgraded to Quill v2 and encounter HTML that was generated from Quill v1.
=> Add support for v1 list attributes

CHANGELOG.md, packages/quill/src/core/quill.ts, packages/quill/test/unit/core/quill.spec.ts
Hi,
as we see on the v2 web site, theme toolbar's handlers (like image) are overwritten, and quill uses the default handler instead.
The fix :  quill.ts, "special case toolbar shortend" was called too late.
We can also see this difference in the code between v2.0 and v1.3.7
Thanks,
=> image selector fix

packages/quill/src/core/quill.ts, packages/quill/test/types/quill.test-d.ts
my current quill version: `v2.0.0`.
as in v2, quill provides its own bundled dts file for developers, but some methods under the `Quill` scope are incorrectly typed due to `Function.call()` will returns an `any` type.
e.g., `quill.updateContents()`, its return type should be `Delta`, but in quill.d.ts, the signature is
```typescript
declare class Quill {
updateContents(delta: Delta | Op[], source?: EmitterSource): any;
}
```
this pr solves the problem by explicitly declaring the return type, and improve dts type tests
=> Improve typings for methods that return a Delta

packages/website/src/pages/docs.jsx
closes #4173 
This PR adds a `docs.jsx` component under `packages/website/src/pages` to match the `/docs` route and then redirects to the first URL provided by `packages/website/src/data/docs.tsx` , the same way as `packages/website/src/pages/playgroud.jsx` does
=> Respond to `/docs` route and do redirection

packages/quill/src/core/module.ts, packages/quill/src/modules/toolbar.ts, packages/quill/src/themes/bubble.ts, packages/quill/src/themes/snow.ts
=> Fix event source when deleting a link with shortcuts

packages/quill/src/modules/keyboard.ts
=> Avoid side effects for Enter/Backspace when composing in Safari

packages/website/content/docs/installation.mdx
Some minor typo fixes I found while reading the docs!
=> Fixed a few typos in docs/installation.mdx
