slab/quill

- src/modules/link-tooltip.coffee
> Bind meta+K to toggle the link tooltip popup, v2

- src/modules/image-tooltip.coffee
- src/modules/link-tooltip.coffee
- src/modules/tooltip.coffee
A collection of small changes to the link-tooltip module. All are teensy UX improvements my users have asked for after some experience using quill.
> Fix link tooltip

- src/core/format.coffee
This fixes an issue where applying list formatting multiple times causes nested OL tags to be created.
> Fix an issue with formats with parentTag

- core/editor.js
- test/unit/editor.js
> Fixed issue where applyDelta didn't work when given an insert with attributes

- core/quill.js
- test/unit/quill.js
This improves backwards compatibility with the 0.20 which supported this. Unit tests attached.
> Support setContents with json

- modules/link-tooltip.js
- modules/toolbar.js
We were getting a "Quill is undefined" error.
> Swapping Quill global references with 'Emitter

- docs/docs/api/selection.md
> fix getSelection example in API docs

- core/quill.js
- test/unit/core/quill.js
> Allow more falsey values for the theme property

- themes/base.js
> Use lowercase characters for all colors

- formats/image.js
> Support `alt` attribute for image format

- README.md
Filed under 'Quick typo fix or documentation improvement' in the guidelines.
> Added a 'live demo' link for easy appraisal

- docs/docs/modules/clipboard.md
Super minor but the `Edit on GitHub` was so close to reach I figured I'd just apply the change. 😀
> Minor typo

- core/quill.js
> Make sure the `ql-blank` gets always removed when editor has content

- docs/guides/upgrading-to-1-0.md
These are based on my observations/experience -- needs review to confirm that these are indeed correct. They're breaking changes, so would be nice to mention.
> Additions to the Upgrading to 1.0 guide

- assets/base.styl
- assets/icons/table-border-all.svg
- assets/icons/table-border-bottom.svg
- assets/icons/table-border-left.svg
- assets/icons/table-border-outside.svg
- assets/icons/table-border-right.svg
- assets/icons/table-border-top.svg
stroke-miterlimit instead of mitter
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-miterlimit
> fix typo in ql-stroke-miter

- themes/base.js
simple one line change to avoid possible troubles
> fixed possible NPE

- assets/core.styl
fix https://github.com/quilljs/quill/issues/1481
> Fix rtl list space

- test/unit/theme/base/tooltip.js
- themes/base.js
Helps confused users that otherwise get a 404 page from the domain they are on. http://i.imgur.com/j41G65y.png
> Default to https when embedding videos

- docs/guides/comparison-with-other-rich-text-editors.md
Revisions to correct English mistakes and make the text easier to understand.
> Revise section text

- docs/docs/api/model.md
Fixed a typo in api/model, line 102.
> Fixed a very very minor typo on line 102. :)

- docs/guides/comparison-with-other-rich-text-editors.md
> Fix typo: Draft -> Quill

- .travis.yml
- _develop/karma.config.js
travis does not add the sauce labs addon for PRs
> fix sauce labs + travis for PRs

- ui/icon-picker.js
> Prevent icon-picker from triggering unnecessary layout reflow

- docs/docs/api/extension.md
disable and enable,is duplicated with editor.md
> fix extension.md

- assets/core.styl
To test:
1. Visit http://127.0.0.1:9000/standalone/full/.
2. Paste the following content:
```
1. test
1. test
* test
1. test
```
3. Make sure the last item's number is correct.
> Other list types should also reset list numbers

- core/selection.js
> Fix selection-change not firing on DOM mutations

- modules/clipboard.ts
- test/unit/modules/clipboard.js
To test:
1. Open http://localhost:9000/standalone/full
2. Copy a code snippet from https://reactjs.org/
3. Make sure newlines are kept.
> Keep newlines in pre tag

- website/content/standalone/stress.mdx
- website/src/components/standalone/SnowEditor.jsx
This PR adds http://localhost:9000/standalone/stress for initial load performance testing.
To test:
Visit http://localhost:9000/standalone/stress, make sure the page and editor load with content.
> Add a standalone page for performance testing

- formats/indent.ts
- test/unit/formats/indent.spec.ts
Indent on develop branch is not working, seems to be caused by https://github.com/quilljs/quill/pull/3845/files#diff-60181b04e70c2478fbc73ef2f9a1a85427d7341e6cb41cc36ba50e29b532c37d missing the case where `indent` is a number
Fixed and added a sanity test case
@luin can you help review? Thanks!
> Fix indent not working

- CHANGELOG.md
- package-lock.json
- packages/quill/package.json
- packages/quill/src/core/emitter.ts
- packages/quill/test/unit/core/emitter.spec.ts
> Fix typing errors for emitter

- CHANGELOG.md
- packages/quill/src/core/quill.ts
- packages/quill/test/unit/core/quill.spec.ts
> Fix Quill.getText not respecting length

- CHANGELOG.md
- packages/quill/src/modules/history.ts
- packages/website/content/docs/modules/keyboard.mdx
> Fix redo shortcut not working on Linux and Windows

- CHANGELOG.md
- packages/quill/src/core/quill.ts
- packages/quill/src/modules/clipboard.ts
- packages/quill/src/modules/history.ts
- packages/quill/test/unit/modules/clipboard.spec.ts
> Support pasting links copied from iOS share sheets

- packages/quill/src/core.ts
- packages/quill/src/core/quill.ts
- packages/quill/src/quill.ts
- packages/quill/test/types/quill.test-d.ts
- packages/quill/test/unit/core/quill.spec.ts
- packages/quill/test/unit/modules/history.spec.ts
- packages/quill/test/unit/modules/syntax.spec.ts
- packages/quill/test/unit/vitest.config.ts
- packages/website/content/docs/api.mdx
> Fix function overloads for formatText

- packages/quill/src/ui/icons.ts
> Fix toolbar icons for h3-h6

- .github/release.yml
- .github/workflows/label.yml
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
> Use labels for changelog generating

- packages/quill/src/modules/uploader.ts
> Ignore pasting images when image format is disallowed

- packages/quill/src/quill.ts
- packages/quill/test/types/quill.test-d.ts
> Export Delta, AttributeMap and other related objects

- .github/workflows/label.yml
- packages/quill/src/blots/text.ts
A quick minior improvement noticed when working on clipboard improvements.
> Avoid unnecessary local map creations
